import Image from "next/image";
import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: "Moustache Republic Hiring Challenge",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
        <Link href="/cart" id="carticon">
          <Image src="/cart.jpg" width={40} height={40} alt="Cart" />
        </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
